language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - nightly

env:
    - EVENT_STORE_VERSION='v3.0.0'
    - EVENT_STORE_VERSION='v3.0.1'
    - EVENT_STORE_VERSION='v3.0.2'
    - EVENT_STORE_VERSION='v3.0.3'
matrix:
    allow_failures:
        - php: hhvm
        - php: nightly

before_install:
    - wget http://download.geteventstore.com/binaries/EventStore-OSS-Linux-${EVENT_STORE_VERSION}.tar.gz
    - tar xf EventStore*.tar.gz
    - cd EventStore* && ./clusternode --mem-db 2>&1> eventstore.log &
install:
    - composer install --dev --prefer-source --no-interaction

script: bin/phpunit --coverage-clover=coverage.clover --coverage-text --testdox

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

after_scripts:
  - killall -SIGINT clusternode
  - cat EventStore*/eventstore.log
